# Generated by Django 5.1 on 2025-01-30 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0009_reportemunicipal_reporte_ciudadano'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporeporte',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad_municipal_app.departamento'),
        ),
    ]
