# Generated by Django 5.1 on 2025-02-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_alter_sector_estado_alter_sector_nombre'),
        ('shared', '0006_alter_notificacion_titulo'),
    ]

    operations = [
    ]
