# Generated by Django 5.1 on 2025-02-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_merge_20250204_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='estado',
            field=models.CharField(choices=[('SEGURO', 'Seguro'), ('PRECAUCIÓN', 'Precaución'), ('RIESGO', 'Riesgo')], default='SEGURO', help_text='Estado actual del sector (Seguro, Precaución, Riesgo)', max_length=20, verbose_name='Estado del Sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nombre',
            field=models.CharField(choices=[('BELISARIO QUEVEDO', 'Belisario Quevedo'), ('EL INCA', 'El Inca'), ('CARCELÉN', 'Carcelén'), ('CENTRO HISTÓRICO', 'Centro Histórico'), ('CHILIBULO', 'Chilibulo'), ('CHILLOGALLO', 'Chillogallo'), ('CHIMBACALLE', 'Chimbacalle'), ('COCHAPAMBA', 'Cochapamba'), ('COMITÉ DEL PUEBLO', 'Comité del Pueblo'), ('CONCEPCIÓN', 'Concepción'), ('COTOCOLLAO', 'Cotocollao'), ('EL CONDADO', 'El Condado'), ('MAGDALENA', 'Magdalena'), ('GUAMANÍ', 'Guamaní'), ('IÑAQUITO', 'Iñaquito'), ('ITCHIMBÍA', 'Itchimbía'), ('JIPIJAPA', 'Jipijapa'), ('KENNEDY', 'Kennedy'), ('LA ARGELIA', 'La Argelia'), ('LA ECUATORIANA', 'La Ecuatoriana'), ('LA FERROVIARIA', 'La Ferroviaria'), ('LA LIBERTAD', 'La Libertad'), ('LA MENA', 'La Mena'), ('MARISCAL SUCRE', 'Mariscal Sucre'), ('PONCEANO', 'Ponceano'), ('PUENGASÍ', 'Puengasí'), ('QUITUMBE', 'Quitumbe'), ('RUMIPAMBA', 'Rumipamba'), ('SAN BARTOLO', 'San Bartolo'), ('SAN JUAN', 'San Juan'), ('SOLANDA', 'Solanda'), ('TURUBAMBA', 'Turubamba')], help_text='Nombre único del sector', max_length=100, unique=True, verbose_name='Nombre del Sector'),
        ),
    ]
