# Generated by Django 5.1 on 2025-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_alter_sector_estado_alter_sector_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
        migrations.AddField(
            model_name='sector',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='estado',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nombre',
            field=models.CharField(choices=[('BELISARIO QUEVEDO', 'Belisario Quevedo'), ('EL INCA', 'El Inca'), ('CARCELÉN', 'Carcelén'), ('CENTRO HISTÓRICO', 'Centro Histórico'), ('CHILIBULO', 'Chilibulo'), ('CHILLOGALLO', 'Chillogallo'), ('CHIMBACALLE', 'Chimbacalle'), ('COCHAPAMBA', 'Cochapamba'), ('COMITÉ DEL PUEBLO', 'Comité del Pueblo'), ('CONCEPCIÓN', 'Concepción'), ('COTOCOLLAO', 'Cotocollao'), ('EL CONDADO', 'El Condado'), ('MAGDALENA', 'La Magdalena'), ('GUAMANÍ', 'Guamaní'), ('IÑAQUITO', 'Iñaquito'), ('ITCHIMBÍA', 'Itchimbía'), ('JIPIJAPA', 'Jipijapa'), ('KENNEDY', 'Kennedy'), ('LA ARGELIA', 'La Argelia'), ('LA ECUATORIANA', 'La Ecuatoriana'), ('LA FERROVIARIA', 'La Ferroviaria'), ('LA LIBERTAD', 'La Libertad'), ('LA MENA', 'La Mena'), ('MARISCAL SUCRE', 'Mariscal Sucre'), ('PONCEANO', 'Ponceano'), ('PUENGASÍ', 'Puengasí'), ('QUITUMBE', 'Quitumbe'), ('RUMIPAMBA', 'Rumipamba'), ('SAN BARTOLO', 'San Bartolo'), ('SAN JUAN', 'San Juan'), ('SOLANDA', 'Solanda'), ('TURUBAMBA', 'Turubamba')], max_length=50, unique=True),
        ),
    ]
