# Generated by Django 5.1 on 2025-01-30 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0003_tiporeporte_reporte'),
        ('entidad_municipal_app', '0006_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeporte',
            name='departamento',
            field=models.ForeignKey(default='EPMMOP', help_text='Departamento al cual se asigna el reporte', on_delete=django.db.models.deletion.CASCADE, to='entidad_municipal_app.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='tiporeporte',
            name='prioridad_de_atencion',
            field=models.IntegerField(default=0),
        ),
    ]
