# Generated by Django 5.1 on 2025-01-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0003_tiporeporte_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica si el ciudadano puede acceder al panel de administración', verbose_name='¿Es Personal Administrativo?'),
        ),
    ]
