# Generated by Django 5.1 on 2025-01-28 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0003_tiporeporte_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(default='Área Comunal', help_text='Nombre del área comunal', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='ciudadano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
