# Generated by Django 5.1 on 2025-01-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0003_tiporeporte_reporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporte',
        ),
        migrations.DeleteModel(
            name='TipoReporte',
        ),
    ]
