# Generated by Django 5.1 on 2025-01-30 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0004_tiporeporte_departamento_and_more'),
        ('entidad_municipal_app', '0006_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporeporte',
            name='departamento',
            field=models.ForeignKey(default=1, help_text='Departamento al cual se asigna el reporte', on_delete=django.db.models.deletion.CASCADE, to='entidad_municipal_app.departamento', verbose_name='Departamento'),
        ),
    ]
