# Generated by Django 5.1 on 2025-01-28 23:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0004_areacomunal_reserva_ciudadano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='id',
        ),
        migrations.AddField(
            model_name='areacomunal',
            name='hora_de_apertura',
            field=models.TimeField(default=datetime.time(7, 0), help_text='Hora de apertura del área comunal', null=True),
        ),
        migrations.AddField(
            model_name='areacomunal',
            name='hora_de_cierre',
            field=models.TimeField(default=datetime.time(20, 0), help_text='Hora de cierre del área comunal', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='area_comunal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='ciudadano_app.areacomunal'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='correos_invitados',
            field=models.CharField(default='', help_text='Correos de los invitados', max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(help_text='Fecha de la reserva', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(help_text='Hora de fin de la reserva', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(help_text='Hora de inicio de la reserva', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.CharField(help_text='Tipo de reserva', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='ciudadano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
