# Generated by Django 5.1 on 2025-01-29 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0004_auto_20250128_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudadano',
            name='es_staff',
        ),
    ]
