# Generated by Django 5.1 on 2025-01-29 14:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0005_remove_reserva_id_areacomunal_hora_de_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomunal',
            name='hora_de_apertura',
            field=models.TimeField(default=datetime.time(7, 0), help_text='Hora de apertura del área comunal'),
        ),
        migrations.AlterField(
            model_name='areacomunal',
            name='hora_de_cierre',
            field=models.TimeField(default=datetime.time(20, 0), help_text='Hora de cierre del área comunal'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='area_comunal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ciudadano_app.areacomunal'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(help_text='Fecha de la reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(help_text='Hora de fin de la reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(help_text='Hora de inicio de la reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.CharField(help_text='Tipo de reserva', max_length=50),
        ),
    ]
