# Generated by Django 5.1 on 2025-01-30 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0005_alter_tiporeporte_departamento'),
        ('entidad_municipal_app', '0007_remove_departamento_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporeporte',
            name='departamento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad_municipal_app.departamento'),
        ),
    ]
