# Generated by Django 5.1 on 2025-01-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0005_remove_ciudadano_es_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudadano',
            options={'verbose_name': 'Ciudadano', 'verbose_name_plural': 'Ciudadanos'},
        ),
        migrations.AlterModelTable(
            name='ciudadano',
            table='ciudadano_app_ciudadano',
        ),
    ]
