# Generated by Django 5.1 on 2025-01-29 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0006_alter_ciudadano_options_alter_ciudadano_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudadano',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema asociado al ciudadano', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudadano', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudadano_app.ciudadano'),
        ),
    ]
