# Generated by Django 5.1 on 2025-01-29 22:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0006_alter_areacomunal_hora_de_apertura_and_more'),
        ('entidad_municipal_app', '0008_alter_entidadmunicipal_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomunal',
            name='espacio_publico',
            field=models.ForeignKey(default=1, help_text='Espacio público al que pertenece el área comunal', on_delete=django.db.models.deletion.CASCADE, related_name='areas_comunales', to='entidad_municipal_app.espaciopublico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(default='Activa', help_text='Estado de la reserva', max_length=50),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areacomunal',
            name='hora_de_cierre',
            field=models.TimeField(default=datetime.time(19, 0), help_text='Hora de cierre del área comunal'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='area_comunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ciudadano_app.areacomunal'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
    ]
