# Generated by Django 5.1 on 2025-01-30 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0006_alter_tiporeporte_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiporeporte',
            name='departamento',
        ),
    ]
