# Generated by Django 5.1 on 2025-01-30 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0007_remove_tiporeporte_departamento'),
        ('entidad_municipal_app', '0008_reportemunicipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeporte',
            name='departamento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad_municipal_app.departamento'),
        ),
    ]
