# Generated by Django 5.1 on 2025-01-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0004_delete_reporte_delete_tiporeporte'),
        ('ciudadano_app', '0007_areacomunal_espacio_publico_reserva_estado_reserva_and_more'),
    ]

    operations = [
    ]
