# Generated by Django 5.1 on 2025-01-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0008_tiporeporte_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiporeporte',
            name='departamento',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
        migrations.DeleteModel(
            name='TipoReporte',
        ),
    ]
