# Generated by Django 5.1 on 2025-01-26 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(help_text='Nombre descriptivo del evento municipal', max_length=200, verbose_name='Nombre del Evento')),
                ('descripcion_evento', models.TextField(help_text='Descripción detallada del evento', verbose_name='Descripción')),
                ('fecha_realizacion', models.DateTimeField(help_text='Fecha y hora en que se realizará el evento', verbose_name='Fecha de Realización')),
                #('lugar_evento', models.CharField(help_text='Ubicación donde se realizará el evento', max_length=200, verbose_name='Lugar')),
                ('capacidad_maxima', models.PositiveIntegerField(help_text='Número máximo de personas que pueden asistir', verbose_name='Capacidad Máxima')),
                ('cupos_disponibles', models.PositiveIntegerField(help_text='Número de cupos aún disponibles', verbose_name='Cupos Disponibles')),
                ('estado_actual', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', help_text='Estado actual del evento', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro del evento', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Evento Municipal',
                'verbose_name_plural': 'Eventos Municipales',
                'ordering': ['-fecha_realizacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_registro', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('EN_ESPERA', 'En Lista de Espera'), ('CANCELADO', 'Cancelado'), ('ASISTIO', 'Asistió'), ('NO_ASISTIO', 'No Asistió')], help_text='Estado actual de la inscripción', max_length=20, verbose_name='Estado del Registro')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la inscripción', verbose_name='Fecha de Inscripción')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última Actualización')),
                ('ciudadano', models.ForeignKey(help_text='Ciudadano que se inscribe al evento', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ciudadano')),
                ('evento', models.ForeignKey(help_text='Evento al que se inscribe el ciudadano', on_delete=django.db.models.deletion.CASCADE, to='entidad_municipal_app.eventomunicipal', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['fecha_inscripcion'],
                'unique_together': {('ciudadano', 'evento')},
            },
        ),
    ]
