# Generated by Django 5.1 on 2025-01-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventomunicipal',
            name='cupos_disponibles',
        ),
    ]
