# Generated by Django 5.1 on 2025-01-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0002_remove_eventomunicipal_cupos_disponibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasistencia',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última Modificación'),
        ),
        migrations.AlterField(
            model_name='eventomunicipal',
            name='estado_actual',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', help_text='Estado actual del evento', max_length=20, verbose_name='Estado del Evento'),
        ),
    ]
