# Generated by Django 5.1 on 2025-01-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0003_remove_registroasistencia_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
