# Generated by Django 5.1 on 2025-01-27 00:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0004_entidadmunicipal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidadmunicipal',
            options={'verbose_name': 'Entidad Municipal', 'verbose_name_plural': 'Entidades Municipales'},
        ),
        migrations.AddField(
            model_name='entidadmunicipal',
            name='correo_electronico',
            field=models.EmailField(default='contacto@entidad.com', help_text='Correo electrónico de contacto', max_length=254),
        ),
        migrations.AddField(
            model_name='entidadmunicipal',
            name='direccion',
            field=models.CharField(default='Dirección no especificada', help_text='Dirección física de la entidad', max_length=200),
        ),
        migrations.AddField(
            model_name='entidadmunicipal',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de registro en el sistema'),
        ),
        migrations.AddField(
            model_name='entidadmunicipal',
            name='nombre',
            field=models.CharField(default='Entidad Municipal', help_text='Nombre de la entidad municipal', max_length=100),
        ),
        migrations.AddField(
            model_name='entidadmunicipal',
            name='telefono',
            field=models.CharField(default='000-000-0000', help_text='Número de teléfono de contacto', max_length=20),
        ),
    ]
