# Generated by Django 5.1 on 2025-01-29 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0007_remove_ciudadano_groups_and_more'),
        ('entidad_municipal_app', '0005_alter_entidadmunicipal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='ciudadano',
            field=models.ForeignKey(help_text='Ciudadano que se inscribe al evento', on_delete=django.db.models.deletion.CASCADE, to='ciudadano_app.ciudadano', verbose_name='Ciudadano'),
        ),
    ]
