# Generated by Django 5.1 on 2025-01-28 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0005_alter_entidadmunicipal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Espacio Público', help_text='Nombre del espacio público', max_length=100)),
                ('entidad_municipal', models.ForeignKey(help_text='Entidad municipal a la que pertenece el espacio público', on_delete=django.db.models.deletion.CASCADE, to='entidad_municipal_app.entidadmunicipal')),
            ],
        ),
    ]
