# Generated by Django 5.1 on 2025-01-28 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0006_espaciopublico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='correo_electronico',
            field=models.EmailField(default='contacto@entidad.com', help_text='Correo electrónico de contacto', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='direccion',
            field=models.CharField(default='Dirección no especificada', help_text='Dirección física de la entidad', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de registro en el sistema', null=True),
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='nombre',
            field=models.CharField(default='Entidad Municipal', help_text='Nombre de la entidad municipal', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='telefono',
            field=models.CharField(default='000-000-0000', help_text='Número de teléfono de contacto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='espaciopublico',
            name='entidad_municipal',
            field=models.ForeignKey(help_text='Entidad municipal a la que pertenece el espacio público', null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad_municipal_app.entidadmunicipal'),
        ),
        migrations.AlterField(
            model_name='espaciopublico',
            name='nombre',
            field=models.CharField(default='Espacio Público', help_text='Nombre del espacio público', max_length=100, null=True),
        ),
    ]
