# Generated by Django 5.1 on 2025-01-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0006_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='fecha_creacion',
        ),
    ]
