# Generated by Django 5.1 on 2025-01-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0007_eventomunicipal_entidad_municipal_espaciopublico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventomunicipal',
            name='entidad_municipal',
        ),
    ]
