# Generated by Django 5.1 on 2025-01-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0007_remove_departamento_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMunicipal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='no_asignado', help_text='Estado actual del reporte municipal', max_length=50, verbose_name='Estado')),
                ('evidencia', models.TextField(blank=True, help_text='Evidencia de la atención o resolución del reporte', null=True, verbose_name='Evidencia')),
            ],
            options={
                'verbose_name': 'Reporte Municipal',
                'verbose_name_plural': 'Reportes Municipales',
                'ordering': ['-id'],
            },
        ),
    ]
