# Generated by Django 5.1 on 2025-01-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0008_remove_eventomunicipal_entidad_municipal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espaciopublico',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='espaciopublico',
            name='estado_espacioPublico',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NO_DISPONIBLE', 'No Disponible')], default='DISPONIBLE', help_text='Estado del espacio público en la fecha especificada', max_length=20),
        ),
    ]
