# Generated by Django 5.1 on 2025-01-30 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0008_reportemunicipal'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemunicipal',
            name='reporte_ciudadano',
            field=models.ForeignKey(blank=True, default=None, help_text='Reporte ciudadano original', null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.reporte', verbose_name='Reporte Ciudadano'),
        ),
    ]
