# Generated by Django 5.1 on 2025-01-30 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0009_remove_espaciopublico_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaciopublico',
            name='estado_espacio',
            field=models.CharField(choices=[('Afectado', 'Afectado'), ('No Afectado', 'No Afectado')], default='No Afectado', help_text='Estado del espacio público', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventomunicipal',
            name='lugar_evento',
            field=models.ForeignKey(blank=True, help_text='Espacio público donde se realizará el evento', null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad_municipal_app.espaciopublico', verbose_name='Lugar'),
        ),
    ]
