# Generated by Django 5.1 on 2025-01-30 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0006_canalinformativo_noticia_comentario_reaccion_and_more'),
        ('entidad_municipal_app', '0009_reportemunicipal_reporte_ciudadano'),
    ]

    operations = [
    ]
