# Generated by Django 5.1 on 2025-01-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0010_espaciopublico_estado_espacio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espaciopublico',
            old_name='estado_espacio',
            new_name='estado_incedente_espacio',
        ),
    ]
