# Generated by Django 5.1 on 2025-01-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0009_merge_20250129_2214'),
        ('entidad_municipal_app', '0010_merge_20250129_2318'),
    ]

    operations = [
    ]
