# Generated by Django 5.1 on 2025-01-31 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0009_remove_ciudadano_groups_and_more'),
        ('entidad_municipal_app', '0011_merge_20250130_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ciudadano_app.ciudadano'),
        ),
        migrations.AlterField(
            model_name='espaciopublico',
            name='entidad_municipal',
            field=models.ForeignKey(help_text='Entidad municipal a la que pertenece el espacio público', on_delete=django.db.models.deletion.CASCADE, related_name='espacios_publicos', to='entidad_municipal_app.entidadmunicipal'),
        ),
        migrations.AlterField(
            model_name='reaccion',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='ciudadano_app.ciudadano'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='ciudadano',
            field=models.ForeignKey(help_text='Ciudadano que se inscribe al evento', on_delete=django.db.models.deletion.CASCADE, to='ciudadano_app.ciudadano', verbose_name='Ciudadano'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='ciudadano_app.ciudadano'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['estado_registro'], name='entidad_mun_estado__0aecf5_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['fecha_inscripcion'], name='entidad_mun_fecha_i_dd8824_idx'),
        ),
    ]
