# Generated by Django 5.1 on 2025-01-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0012_alter_comentario_ciudadano_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidadmunicipal',
            options={},
        ),
        migrations.AddField(
            model_name='entidadmunicipal',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la entidad está activa'),
        ),
        migrations.AddField(
            model_name='entidadmunicipal',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica si la entidad tiene acceso al panel de administración'),
        ),
        migrations.AddField(
            model_name='entidadmunicipal',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='entidadmunicipal',
            name='password',
            field=models.CharField(default='default_password', help_text='Password', max_length=128),
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='correo_electronico',
            field=models.EmailField(help_text='Correo electrónico de la entidad', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='direccion',
            field=models.CharField(help_text='Dirección física de la entidad', max_length=200),
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en el sistema'),
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='nombre',
            field=models.CharField(help_text='Nombre de la entidad municipal', max_length=100),
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='telefono',
            field=models.CharField(help_text='Número de teléfono de contacto', max_length=20),
        ),
    ]
