# Generated by Django 5.1 on 2025-02-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0013_alter_entidadmunicipal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
