# Generated by Django 5.1 on 2025-02-01 17:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0013_alter_entidadmunicipal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaciopublico',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ubicación donde se encuentra el espacio público', max_length=200, verbose_name='Lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espaciopublico',
            name='estado_espacio_publico',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NO_DISPONIBLE', 'No Disponible')], default='DISPONIBLE', help_text='Estado del espacio público en la fecha especificada', max_length=20),
        ),
        migrations.AddField(
            model_name='espaciopublico',
            name='estado_incidente_espacio',
            field=models.CharField(choices=[('AFECTADO', 'Afectado'), ('NO_AFECTADO', 'No Afectado')], default='NO_AFECTADO', help_text='Estado del espacio público', max_length=20),
        ),
        migrations.AddField(
            model_name='eventomunicipal',
            name='espacio_publico',
            field=models.ForeignKey(blank=True, help_text='Espacio público donde se realizará el evento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='entidad_municipal_app.espaciopublico', verbose_name='Espacio Público'),
        ),
        migrations.AddField(
            model_name='eventomunicipal',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default='', help_text='Razón por la que se canceló el evento', max_length=200, null=True, verbose_name='Motivo de Cancelación'),
        ),
    ]
