# Generated by Django 5.1 on 2025-02-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0016_merge_20250201_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomunicipal',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default='', help_text='Razón por la que se canceló el evento', max_length=200, verbose_name='Motivo de Cancelación'),
        ),
    ]
