# Generated by Django 5.1 on 2025-02-02 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0017_alter_eventomunicipal_motivo_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventomunicipal',
            name='entidad_municipal',
            field=models.ForeignKey(blank=True, help_text='Entidad municipal que organiza el evento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidad', to='entidad_municipal_app.entidadmunicipal', verbose_name='Entidad Municipal'),
        ),
    ]
