# Generated by Django 5.1 on 2025-02-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('entidad_municipal_app', '0020_merge_20250203_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece este usuario.', related_name='entidad_municipal_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='entidad_municipal_permissions', to='auth.permission'),
        ),
    ]
