# Generated by Django 5.1 on 2025-02-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('entidad_municipal_app', '0020_merge_20250203_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece este usuario.', related_name='entidad_municipal_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='entidadmunicipal',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='entidad_municipal_permissions', to='auth.permission'),
        ),
    ]
