# Generated by Django 5.1 on 2025-02-10 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0010_ciudadano_sector_ciudadano_sectores_de_interes_and_more'),
        ('entidad_municipal_app', '0021_sugerencia_alter_entidadmunicipal_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sugerencia',
            old_name='estado',
            new_name='canal_creado',
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='ciudadano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='ciudadano_app.ciudadano'),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='entidad_municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='entidad_municipal_app.entidadmunicipal'),
        ),
    ]
