# Generated by Django 5.1 on 2025-02-05 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0021_alter_registroasistencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='evento',
            field=models.ForeignKey(help_text='Evento al que se registra el ciudadano', on_delete=django.db.models.deletion.CASCADE, related_name='registroasistencia_set', to='entidad_municipal_app.eventomunicipal', verbose_name='Evento'),
        ),
    ]
