# Generated by Django 5.1 on 2025-02-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0011_remove_ciudadano_sector_and_more'),
        ('entidad_municipal_app', '0021_alter_entidadmunicipal_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroasistencia',
            options={'ordering': ['-fecha_inscripcion'], 'verbose_name': 'Registro de Asistencia', 'verbose_name_plural': 'Registros de Asistencia'},
        ),
        migrations.RemoveField(
            model_name='registroasistencia',
            name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='estado_asistencia',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASISTIO', 'Asistio'), ('NO_ASISTIO', 'No_Asistio')], default='PENDIENTE', help_text='Estado de asistencia del ciudadano al evento', max_length=20, verbose_name='Estado de asistencia'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='eventomunicipal',
            name='estado_actual',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En_Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', help_text='Estado actual del evento', max_length=20, verbose_name='Estado del Evento'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='ciudadano',
            field=models.ForeignKey(help_text='Ciudadano que se registra al evento', on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='ciudadano_app.ciudadano', verbose_name='Ciudadano'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado_registro',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('EN_ESPERA', 'En_Espera'), ('CANCELADO', 'Cancelado')], default='INSCRITO', help_text='Estado actual del registro de asistencia', max_length=20, verbose_name='Estado del registro'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='evento',
            field=models.ForeignKey(help_text='Evento al que se registra el ciudadano', on_delete=django.db.models.deletion.CASCADE, related_name='registroasistencia_set', to='entidad_municipal_app.eventomunicipal', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó el registro', verbose_name='Fecha de inscripción'),
        ),
        migrations.AddIndex(
            model_name='eventomunicipal',
            index=models.Index(fields=['estado_actual'], name='entidad_mun_estado__999755_idx'),
        ),
        migrations.AddIndex(
            model_name='eventomunicipal',
            index=models.Index(fields=['fecha_realizacion'], name='entidad_mun_fecha_r_e2dcd0_idx'),
        ),
    ]
