# Generated by Django 5.1 on 2025-02-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0022_alter_registroasistencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventomunicipal',
            name='cupo_minimo',
            field=models.PositiveIntegerField(default=2, help_text='Número mínimo de inscritos requeridos para que el evento se programe', verbose_name='Cupo Mínimo'),
        ),
        migrations.AlterField(
            model_name='eventomunicipal',
            name='estado_actual',
            field=models.CharField(choices=[('POR_PROGRAMAR', 'Por_Programar'), ('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En_Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', help_text='Estado actual del evento', max_length=20, verbose_name='Estado del Evento'),
        ),
    ]
