# Generated by Django 5.1 on 2025-02-10 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0010_ciudadano_sector_ciudadano_sectores_de_interes_and_more'),
        ('entidad_municipal_app', '0022_rename_estado_sugerencia_canal_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='ciudadano',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='ciudadano_app.ciudadano'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='entidad_municipal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='entidad_municipal_app.entidadmunicipal'),
            preserve_default=False,
        ),
    ]
