# Generated by Django 5.1 on 2025-02-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0023_alter_sugerencia_ciudadano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
