# Generated by Django 5.1 on 2025-02-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0021_alter_entidadmunicipal_groups_and_more'),
        ('entidad_municipal_app', '0023_registroasistencia_estado_asistencia_and_more'),
    ]

    operations = [
    ]
