# Generated by Django 5.1 on 2025-02-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0024_sugerencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
    ]
