# Generated by Django 5.1.6 on 2025-02-11 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0024_merge_20250205_0457'),
        ('entidad_municipal_app', '0025_alter_sugerencia_estado'),
    ]

    operations = [
    ]
